***Variables***

${title}    header

${button_procced_checkout}             //*[@id="center_column"]/p[2]/a[1]/span
${button_procced_checkout_adress}      //*[@id="center_column"]/form/p/button
${button_procced_checkout_shipping}    //*[@id="form"]/p/button
${checkbox_agree_terms}                //*[@id="cgv"]
${button_pay_by_bank_wire}             //*[@id="HOOK_PAYMENT"]/div[1]/div/p/a
${button_confirm_my_order}             //*[@id="cart_navigation"]/button
