***Variables***

${title}                   header
${title_catalogo}          //*[@id="layered_block_left"]/p
${menu_bar}                //*[@id="columns"]/div[1]
${icon_grid}               //*[@id="grid"]
${products_list_grid}      //*[@id="center_column"]/ul
${icon_list}               //*[@id="list"]
${img_carregando}          //*[@id="center_column"]/ul/p/img
${sort_by_lowest_first}    //*[@id="selectProductSort"]/option[2]
${combo_sort_by}           //*[@id="selectProductSort"]